on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Validate ARM Template
        run: |
          az deployment group validate \
          --subscription ${{ secrets.SUBSCRIPTION_ID }} \
          --resource-group NewResourceGroup \
          --template-file DeployLogicApp/LogicApp.json \
          --parameters @DeployLogicApp/LogicApp.parameters.json

      - name: Deploy Logic App ARM Template
        run: |
          az deployment group create \
            --subscription ${{ secrets.SUBSCRIPTION_ID }} \
            --resource-group NewResourceGroup \
            --template-file DeployLogicApp/LogicApp.json \
            --parameters @DeployLogicApp/LogicApp.parameters.json
