name: Deploy Logic App ARM Template

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        run: az login --service-principal -u ${{ secrets.2bd1d0a4-f88a-4baa-bf45-f6b4623c5859 }} -p ${{ secrets.ir28Q~vWRD30Cm_A.tH_yQ1yaI4EEmJOOFSYZc65 }} --tenant ${{ secrets.08fdfb44-3c18-4aa7-9519-72bddc98ad3a }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.23dedca3-2d6f-4822-a69c-d354f6f9e298 }}

      - name: Deploy Logic App ARM Template
        run: |
          az deployment group create \
            --resource-group "NewResourceGroup" \
            --template-file DeployLogicApp/LogicApp.json \
            --parameters @DeployLogicApp/LogicApp.parameters.json
