name: Deploy Logic App ARM Template

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Deploy Logic App ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
          template: ./ARMTemplates/LA_Standard_Basic.json
          parameters: ./ARMTemplates/LA_Standard_Basic_Param.json
