name: Deploy Logic App ARM Template

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUBSCRIPTION_ID: 23dedca3-2d6f-4822-a69c-d354f6f9e298

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          allow-no-subscriptions: true


      - name: Deploy Logic App ARM Template
        run: |
          az deployment group create \
            --Subscription $SUBSCRIPTION_ID \
            --resource-group NewResourceGroup \
            --template-file DeployLogicApp/LogicApp.json \
            --parameters @DeployLogicApp/LogicApp.parameters.json
