on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
     ENV_RESOURCEGROUP: az-logicapp-githubactions-demo-rg
     ENV_RESOURCEGROUPLOCATION: australiaeast
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Create Resource Group
        run: az group create -n ${{env.ENV_RESOURCEGROUP}} -l ${{env.ENV_RESOURCEGROUPLOCATION}}

    
      - name: Validate ARM template
        run: |
         az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --mode Incremental --template-file ./DeployLogicApp/LogicApp.json --parameters ./DeployLogicApp/LogicApp.parameters.json
         
      - name: Deploy Logic App
        run: |
         echo "::set-env name=logicappurl::$(az deployment group create -g az-logicapp-githubactions-demo-rg --template-file ./src/Deployment/azure-logicapp-demo.deploy.json --parameters ./src/Deployment/azure-logicapp-demo.deploy.parameters.json --query 'properties.outputs.logicAppUrl.value' -o tsv)"
         shell: bash 
      - name: Logout
        run: az logout
